services:
  - type: web
    name: study-motivator-agent
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
